import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import GlobalContextProvider from "@/contexts/ContextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DevSnippets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <GlobalContextProvider>
          <body className={`inter.className bg-[#121213]`}>
            {children}
          </body>
        </GlobalContextProvider>
      </ClerkProvider>
    </html>
  );
}
